version: 2.1

jobs:
  "Build":
    docker:
      - image: chraac/pico-builder:latest
    steps:
      - checkout
      - run:
          name: "Build with pico sdk"
          command: "mkdir -p build && cd build && cmake .. && make"

workflows:
  pico-pwm-controller-workflow:
    jobs:
      - Build
