version: 2.1

jobs:
  "Build pico":
    docker:
      - image: chraac/pico-builder:latest
    steps:
      - checkout
      - run:
          name: "Checkout pico sdk"
          command: "git clone -b 1.3.0 https://github.com/raspberrypi/pico-sdk.git /pico/pico-sdk"
      - run:
          name: "Update sdk submodule"
          command: "cd /pico/pico-sdk && git submodule update --init"
      - run:
          name: "Setup build directory"
          command: mkdir -p build
      - run:
          name: "Build debug"
          command: "cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug && make -j8"
          environment: 
            PICO_BASE_PATH: '/pico'
            PICO_SDK_PATH: '/pico/pico-sdk'
      - run:
          name: "Cleanup"
          command: rm -rf build/*
      - run:
          name: "Build release"
          command: "cd build && cmake .. -DCMAKE_BUILD_TYPE=Release && make -j8"
          environment: 
            PICO_BASE_PATH: '/pico'
            PICO_SDK_PATH: '/pico/pico-sdk'
      - store_artifacts:
          path: build/main/pwm_controller.elf
      - store_artifacts:
          path: build/main/pwm_controller.elf.map
      - store_artifacts:
          path: build/main/pwm_controller.uf2
      - store_artifacts:
          path: build/main/pwm_controller.bin
      - store_artifacts:
          path: build/main/pwm_controller.hex
  "Build esp32":
    docker:
      - image: espressif/idf:v4.4.1
        environment: 
          LANG: 'en_US.UTF-8'
          IDF_TARGET: 'esp32c3'
    steps:
      - checkout
      - run:
          name: "Build debug"
          command: $IDF_TOOLS_PATH/entrypoint.sh idf.py -DCMAKE_BUILD_TYPE=Debug -v build
      - run:
          name: "Cleanup"
          command: rm -rf build/*
      - run:
          name: "Build release"
          command: $IDF_TOOLS_PATH/entrypoint.sh idf.py -DCMAKE_BUILD_TYPE=Release build

workflows:
  pico-pwm-controller-workflow:
    jobs:
      - "Build pico"
      - "Build esp32"
