version: 2.1

jobs:
  "Build":
    docker:
      - image: chraac/pico-builder:latest
    steps:
      - checkout
      - run:
          name: "Checkout pico sdk"
          command: "git clone -b 1.3.0 https://github.com/raspberrypi/pico-sdk.git /pico/pico-sdk"
      - run:
          name: "Update sdk submodule"
          command: "cd /pico/pico-sdk && git submodule update --init"
      - run:
          name: "Build with pico sdk"
          command: "mkdir -p build && cd build && cmake .. && make"
          environment: 
            PICO_BASE_PATH: '/pico'
            PICO_SDK_PATH: '/pico/pico-sdk'
      - store_artifacts:
          path: build/exec

workflows:
  pico-pwm-controller-workflow:
    jobs:
      - Build
