services:
  pico-builder-compile:
    platform: linux/x86_64
    image: chraac/pico-builder:latest
    environment:
      - LLAMA_CPP_REPO=/pico-pwm-coneroller
    volumes:
      - ..:/pico-pwm-controller
    command:
      - bash
      - -c
      - |
        echo "PICO_SDK_PATH: $$PICO_SDK_PATH"
        cd $$LLAMA_CPP_REPO
        mkdir -p build_debug
        rm -rf build_debug/*
        cd build_debug
        cmake .. -DCMAKE_BUILD_TYPE=Debug
        make -j$$(nproc)
        mkdir -p ../build_release
        rm -rf ../build_release/*
        cd ../build_release
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make -j$$(nproc)
    restart: "no"
