services:
  pico-builder:
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - TAG_NAME=2.1.0
    image: chraac/pico-builder:latest
    command: /bin/bash -c 'env'
    restart: "no"