name: Builder

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-debug:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: chraac/pico-builder:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Configure
      run: mkdir -p build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug
    - name: Build
      run: make
