name: Builder

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-debug:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: chraac/pico-builder:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Configure And Build
        run: mkdir -p build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug && make -j$(nproc)
  build-release:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: chraac/pico-builder:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Configure And Build
        run: mkdir -p build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release && make -j$(nproc)
